latency-wait: "5"
jobscript: "lsf_jobscript.sh"
use-conda: "False"
use-singularity: "False"
printshellcmds: "False"
restart-times: "0"
jobs: "999"
cluster: "lsf_submit.py"
cluster-status: "lsf_status.py"
max-jobs-per-second: "100"
max-status-checks-per-second: "5"
keep-going: "True"
use-envmodules: "True"
